@rootURL = http://localhost:8000


###
GET {{rootURL}}

//User registration
###
POST {{rootURL}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"kabi",
    "lName":"rb",
    "phone":"1234567890",
    "email":"g@gmail.com",
    "password":"as"
}


###
POST {{rootURL}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"g@gmail.com",
    "password":"as"
}